<?php

namespace ContainerPcTumrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExamCreateStateProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\State\Exam\ExamCreateStateProcessor' shared autowired service.
     *
     * @return \App\State\Exam\ExamCreateStateProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Mapper/ApiResourceEntityMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/src/State/Exam/ExamCreateStateProcessor.php';

        return $container->privates['App\\State\\Exam\\ExamCreateStateProcessor'] = new \App\State\Exam\ExamCreateStateProcessor(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
