<?php

namespace ContainerLE54tyC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExamReadStateProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DataProvider\Exam\ExamReadStateProcessor' shared autowired service.
     *
     * @return \App\DataProvider\Exam\ExamReadStateProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/DataProvider/Exam/ExamReadStateProcessor.php';

        return $container->privates['App\\DataProvider\\Exam\\ExamReadStateProcessor'] = new \App\DataProvider\Exam\ExamReadStateProcessor(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
