<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPcTumrh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPcTumrh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPcTumrh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPcTumrh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPcTumrh\App_KernelDevDebugContainer([
    'container.build_hash' => 'PcTumrh',
    'container.build_id' => 'b1e62f39',
    'container.build_time' => 1758388396,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPcTumrh');
